# Generated by Django 5.2.5 on 2025-11-03 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0069_breakdown_rab_jenis_anggaran'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakdown_rab',
            old_name='nama_barang',
            new_name='nama_rincian',
        ),
        migrations.RenameField(
            model_name='jenis_anggaran',
            old_name='nomor_SPK',
            new_name='client',
        ),
        migrations.CreateModel(
            name='Rincian_Logistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.project')),
            ],
        ),
    ]
