# Generated by Django 5.2.5 on 2025-11-03 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0070_rename_nama_barang_breakdown_rab_nama_rincian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rincian_logistik',
            name='breakdown',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='janggadb.breakdown_rab'),
            preserve_default=False,
        ),
    ]
