# Generated by Django 5.2.5 on 2025-11-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0071_rincian_logistik_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggaran',
            name='sisa_anggaran',
            field=models.BigIntegerField(null=True),
        ),
    ]
