# Generated by Django 5.2.5 on 2025-11-04 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0072_alter_anggaran_sisa_anggaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurva_S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('lampiran', models.FileField(blank=True, upload_to='kurvas/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.project')),
            ],
        ),
    ]
