# Generated by Django 5.2.5 on 2025-11-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0073_kurva_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='photo_profile/default.jpg', upload_to='photo_profile/'),
        ),
    ]
