# Generated by Django 5.2.5 on 2025-11-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0074_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurva_s',
            name='tanggal',
            field=models.DateField(auto_now=True),
        ),
    ]
