# Generated by Django 5.2.5 on 2025-11-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0075_alter_kurva_s_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurva_s',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
