# Generated by Django 5.2.5 on 2025-11-05 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0076_alter_kurva_s_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuan_barang',
            name='nama_barang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.rincian_logistik'),
        ),
    ]
