# Generated by Django 5.2.5 on 2025-11-06 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0077_alter_pengajuan_barang_nama_barang'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuan_barang',
            name='anggaran',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='janggadb.anggaran'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuan_barang',
            name='breakdown',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='janggadb.breakdown_rab'),
            preserve_default=False,
        ),
    ]
