# Generated by Django 5.2.5 on 2025-11-06 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0078_pengajuan_barang_anggaran_pengajuan_barang_breakdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakdown_rab',
            name='jenis_anggaran',
        ),
        migrations.AddField(
            model_name='breakdown_rab',
            name='anggaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='janggadb.anggaran'),
        ),
    ]
