# Generated by Django 5.2.5 on 2025-11-06 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0079_remove_breakdown_rab_jenis_anggaran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistik_Weekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('isi', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janggadb.project')),
            ],
        ),
    ]
