# Generated by Django 5.2.5 on 2025-11-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0080_logistik_weekly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring_po',
            name='jumlah',
            field=models.CharField(max_length=100),
        ),
    ]
