# Generated by Django 5.2.5 on 2025-11-06 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0081_alter_monitoring_po_jumlah'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tanggal',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
