# Generated by Django 5.2.5 on 2025-11-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0082_project_tanggal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_report',
            old_name='tampak',
            new_name='harian',
        ),
    ]
