# Generated by Django 5.2.5 on 2025-11-06 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0083_rename_tampak_daily_report_harian'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_report',
            name='tanggal',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
