# Generated by Django 5.2.5 on 2025-11-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janggadb', '0084_daily_report_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='lampiran',
            field=models.FileField(blank=True, upload_to='preorder/'),
        ),
    ]
