from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.register, name="register"),
    path('pm/', views.Project_Manager, name="project-manager"),
    path('pm/projek-db/', views.Project_Manager_PD, name="pm-projekdb"),
    path('pm/projek-db/<str:client>/', views.Project_Manager_PD, name="detail-projek"),
    path('pm/po-request', views.Project_Manager_PR, name="pm-po-request"),
    path('pm/po-request/update-status/<int:id>', views.Project_Manager_updateStatus, name="pm-update"),
    path('logistik/', views.Logistik, name="logistik"),
    path('logistik/status-PO', views.Logistik_Status, name="logistik-status-po"),
    path('logistik/monitoring-PO', views.Logistik_Monitoring, name="logistik-monitoring-po"),
    path('logistik/breakdown-rab', views.Logistik_PB, name="logistik-pengajuan"),
    path('logistik/update-status/<int:id>', views.Logistik_updateStatus, name="logistik-update"),
    path('logistik/stock-opname', views.Logistik_SO, name="logistik-so"),
    path('management/', views.Management, name="management"),
    path('management/projek-baru', views.Management_PB, name="management-projek-baru"),
    path('management/data-invoice', views.Management_DI, name="management-invoice"),
    path('management/invoice-baru', views.Management_IB, name="management-invoice-baru"),
    path('management/update-status/<int:id>', views.Management_updateStatus, name="management-update"),
    path('management/anggaran', views.Management_A, name="management-anggaran"),
    path('management/cek-anggaran', views.Management_AC, name="management-cek-anggaran"),
    path('management/expense', views.Management_E, name="management-expense"),
    path('management/pengajuan-barang', views.Management_P, name="management-pengajuan"),
    path('management/rincian-pekerjaan', views.Management_RP, name="management-rincian"),
    path('management/rincian-logistik', views.Management_RL, name="management-rl"),
    path('admin-jangga/', views.Admin, name="admin-jangga"),
    path('edit-profil/<int:pk>', views.Profil, name="edit-profil"),
    path('change-password/', views.Change_Password, name="change-password"),
    path('admin-jangga/projek-db', views.Admin_PD, name="admin-projekdb"),
    path('admin-jangga/penagihan', views.Admin_P, name="admin-penagihan"),
    path('admin-jangga/mapping-report', views.Admin_MR, name="admin-mapping-report"),
    path('admin-jangga/daily-report', views.Admin_DR, name="admin-daily-report"),
    path('client/', views.Client, name="client"),
    path('client/live-stream', views.Client_Live, name="client-live"),
    path('client/frame', views.video_feed, name="video-feed"),

    path('logout/', views.Logout, name="logout"),
]