from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.register, name="register"),
    path('pm/', views.Project_Manager, name="project-manager"),
    path('pm/projek-db/', views.Project_Manager_PD, name="pm-projekdb"),
    path('pm/projek-db/<str:client>/', views.Project_Manager_PD, name="detail-projek"),
    path('pm/po-request', views.Project_Manager_PR, name="pm-po-request"),
    path('pm/kurvas', views.Project_Manager_KS, name="pm-kurva-s"),
    path('pm/po-request/update-status/<int:id>', views.Project_Manager_updateStatus, name="pm-update"),
    path('logistik/', views.Logistik, name="logistik"),
    path('logistik/pengajuan-barang', views.Logistik_PB, name="logistik-pengajuan"),
    path('logistik/monitoring-PO', views.Logistik_Monitoring, name="logistik-monitoring-po"),
    path('logistik/update-status/<int:id>', views.Logistik_updateStatus, name="logistik-update"),
    path('logistik/stock-opname', views.Logistik_SO, name="logistik-so"),
    path('logistik/get-anggaran/', views.Logistik_get_anggaran, name="get-anggaran"),
    path('logistik/get-breakdown/', views.Logistik_get_breakdown, name='get-breakdown'),
    path('logistik/get-logistik/', views.Logistik_get_logistik, name='get-logistik'),
    path('logistik/weekly-report/', views.Logistik_WR, name='logistik-wr'),
    path('management/', views.Management, name="management"),
    path('management/projek-baru', views.Management_PB, name="management-projek-baru"),
    path('management/data-invoice', views.Management_DI, name="management-invoice"),
    path('management/invoice-baru', views.Management_IB, name="management-invoice-baru"),
    path('management/po', views.Management_PO, name="management-po"),
    path('management/update-invoice/<int:id>', views.Management_updateInvoice, name="update-invoice"),
    path('management/update-pengajuan/<int:id>', views.Management_updatePengajuan, name="update-pengajuan"),
    path('management/anggaran', views.Management_A, name="management-anggaran"),
    path('management/get-jenis-anggaran', views.Management_get_jenis_anggaran, name="get-jenis-anggaran"),
    path('management/cek-anggaran', views.Management_AC, name="management-cek-anggaran"),
    path('management/expense', views.Management_E, name="management-expense"),
    path('management/pengajuan-barang', views.Management_P, name="management-pengajuan"),
    path('management/rincian-pekerjaan', views.Management_RP, name="management-rincian"),
    path('management/rincian-logistik', views.Management_RL, name="management-rl"),
    path('admin-jangga/', views.Admin, name="admin-jangga"),
    path('edit-profil/<int:pk>', views.Profil, name="edit-profil"),
    path('change-password/', views.Change_Password, name="change-password"),
    path('admin-jangga/projek-db', views.Admin_PD, name="admin-projekdb"),
    path('admin-jangga/penagihan', views.Admin_P, name="admin-penagihan"),
    path('admin-jangga/mapping-report', views.Admin_MR, name="admin-mapping-report"),
    path('admin-jangga/daily-report', views.Admin_DR, name="admin-daily-report"),
    path('admin-jangga/kurvas', views.Admin_KS, name="admin-kurva-s"),
    path('client/', views.Client, name="client"),
    path('client/live-stream', views.Client_Live, name="client-live"),
    path('client/frame', views.video_feed, name="video-feed"),
    path('logout/', views.Logout, name="logout"),
]